// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: domain/proto/todo.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TodoRpcClient is the client API for TodoRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TodoRpcClient interface {
	// GetUsers
	FetchTodos(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*FetchTodosResponse, error)
}

type todoRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewTodoRpcClient(cc grpc.ClientConnInterface) TodoRpcClient {
	return &todoRpcClient{cc}
}

func (c *todoRpcClient) FetchTodos(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*FetchTodosResponse, error) {
	out := new(FetchTodosResponse)
	err := c.cc.Invoke(ctx, "/todo.TodoRpc/FetchTodos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoRpcServer is the server API for TodoRpc service.
// All implementations must embed UnimplementedTodoRpcServer
// for forward compatibility
type TodoRpcServer interface {
	// GetUsers
	FetchTodos(context.Context, *EmptyReq) (*FetchTodosResponse, error)
	mustEmbedUnimplementedTodoRpcServer()
}

// UnimplementedTodoRpcServer must be embedded to have forward compatible implementations.
type UnimplementedTodoRpcServer struct {
}

func (UnimplementedTodoRpcServer) FetchTodos(context.Context, *EmptyReq) (*FetchTodosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchTodos not implemented")
}
func (UnimplementedTodoRpcServer) mustEmbedUnimplementedTodoRpcServer() {}

// UnsafeTodoRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TodoRpcServer will
// result in compilation errors.
type UnsafeTodoRpcServer interface {
	mustEmbedUnimplementedTodoRpcServer()
}

func RegisterTodoRpcServer(s grpc.ServiceRegistrar, srv TodoRpcServer) {
	s.RegisterService(&TodoRpc_ServiceDesc, srv)
}

func _TodoRpc_FetchTodos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoRpcServer).FetchTodos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.TodoRpc/FetchTodos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoRpcServer).FetchTodos(ctx, req.(*EmptyReq))
	}
	return interceptor(ctx, in, info, handler)
}

// TodoRpc_ServiceDesc is the grpc.ServiceDesc for TodoRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TodoRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "todo.TodoRpc",
	HandlerType: (*TodoRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchTodos",
			Handler:    _TodoRpc_FetchTodos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "domain/proto/todo.proto",
}
